# Generated by Django 4.2.1 on 2023-12-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cop',
            name='date_retour',
            field=models.DateField(blank=True),
        ),
    ]
