# Generated by Django 4.2.1 on 2023-12-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_cop_date_aller'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='image',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
    ]
