# Generated by Django 4.2.1 on 2023-12-21 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_registeruser_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_sous_off',
            new_name='is_secraiteur',
        ),
    ]
